### ISSUE TITLE
After adding EKF, the effect deteriorates or there is no significant improvement. Is this normal

### ISSUE THREAD

**Issue by wangqin666** [Air-IO/Air-IO#4]
![Image](https://github.com/user-attachments/assets/fc7794e9-624d-480c-82ee-ad4fe2612403)

![Image](https://github.com/user-attachments/assets/734e0008-5279-4f5d-83a3-3f758bd79d11)

**Comment by wangqin666** [comment]
![Image](https://github.com/user-attachments/assets/3d3298c8-905c-4ecb-9afe-1517347f3ddd)

**Comment by haleqiu** [comment]
@wangqin666 Hi, thank you for bringing up this. We updated the code. Please let us know if you have other issues.

**Comment by wangqin666** [comment]
Great, Amazing，thank you for your efforts, but I found that there is no issue with the blackbird dataset anymore; however, the problem still persists in the pegasus dataset. Is it possible that there's an issue with the net_output.pickle of AI_IMU? (I downloaded it from the link you provided for AIIMU.


However, I also have issues with the generation of the orientation_output.pickle file. I am not sure where it comes from, and you included it in the AIIMU compressed package. But when I trained AirIMU, this file was not generated. Could you tell me where it comes from? I will open a new issue.

![Image](https://github.com/user-attachments/assets/7cfd92fc-0dff-4b26-ac8a-660a4ea654c1)

![Image](https://github.com/user-attachments/assets/96d53b0a-dc0a-4279-a30d-2ef8ea4b30e7)

**Comment by wangqin666** [comment]
@haleqiu Great, I guess you also noticed this issue and updated the link for AirIMU. This issue has been resolved and can be closed now. Thank you again. I hope you can answer my question about how orientation_output.pickle is generated, preferably by providing a code example. That would be greatly appreciated!

![Image](https://github.com/user-attachments/assets/6da5e7b5-46d0-44a9-841c-5aa71b198e28)

**Comment by haleqiu** [comment]
Close this issue as completed. The other question should be answered in another issue
